spring:
  dataSource:
    url: jdbc:postgresql://127.0.0.1:5432/companies
    username: ${PG_USER:postgres}
    password: ${PG_PASSWORD:postgres}
  jpa:
    # show SQL statements in console.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    generate_statistics: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: debug
    root: info
  file: log/app.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
