spring:
  dataSource:
    url: jdbc:postgresql://192.168.1.20:5432/companies
    username: postgres
    password: postgres
  jpa:
    # show SQL statements in console.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    generate_statistics: true


